### ISSUE TITLE
`master` doesn't inclue a lot of the fixes from `develop`

### ISSUE THREAD

**Issue by Coaxial** [adhearsion/matrioska#15]
Hi,

`master` doesn't include a lot of the fixes present in `develop`. Any chance to merge the two branches so that the version we get via `bundle install` is up to date?

More specifically this commit: https://github.com/adhearsion/matrioska/commit/80f5939dde8844a791c0f3d981acdede1be8d51d that lets Matrioska use patterns longer than 1 digit.

Cheers,

**Comment by bklang** [comment]
Yes, thanks for prompting. We'll get a release prepared shortly.

**Comment by bklang** [comment]
This has been included in [Matrioska 0.3.0](https://rubygems.org/gems/matrioska)
